theme: jekyll-theme-tactile
name: "Chris Fenner's Personal Blog Name"
title: "Chris Fenner's Personal Blog Title"
description: "Chris Fenner's Personal Blog Description"

defaults:
  -
    scope:
      path: ""
    values:
      author: "Chris Fenner"
