theme: jekyll-theme-tactile
title: "chris fenner's personal blog"
description: "worth the price of admission"
permalink: "/:title"

defaults:
  -
    scope:
      path: ""
    values:
      author: "Chris Fenner"
