title = "Chris Fenner's Personal Blog"
url = "http://dlp.rip"
tagline = "Almost worth the price of admission."

[[posts]]
path = "2021-10-18-tpm-carte-blanche.typ"
title = "TPM Carte Blanche"
tagline = "The true TCB of self-measured BIOS"
permalink = "/tpm-carte-blanche"
preview = "/images/2021-10-18-og.png"
date = 2021-10-18

[[posts]]
path = "2021-10-25-tcb-attestation.typ"
title = "TPM Carte Blanche-resistant Boot Attestation"
tagline = "Some tips for verifiers"
permalink = "/tcb-attestation"
preview = "/images/2021-10-25-og.png"
date = 2021-10-25

[[posts]]
path = "2023-10-01-brick.typ"
title = "The Brick Test"
tagline = "Defining success carefully"
permalink = "/brick"
preview = "/images/2023-10-01-og.png"
date = 2023-10-01

[[posts]]
path = "2024-02-07-tpm-genie.typ"
title = "TPM Genie"
tagline = "BitLocker is Designed to Have This Problem"
permalink = "/tpm-genie"
preview = "/images/2024-02-07-og.png"
date = 2024-02-07

[[posts]]
path = "2024-03-18-attestable-tpm.typ"
title = "Attestable TPMs"
tagline = "Attesting to the TPM's Firmware"
permalink = "/attesting-tpm-firmware"
preview = "/images/2024-03-18-og.png"
date = 2024-03-18

[[posts]]
path = "2026-01-03-decorative-cryptography.typ"
title = "Decorative Cryptography"
tagline = "Some Thoughts on Decorative Cryptography"
permalink = "/decorative-cryptography"
preview = "/images/2026-01-03-og.png"
date = 2026-01-03

[[posts]]
path = "2026-07-20-everyday-cryptography.typ"
title = "The Design of Everyday Cryptography"
tagline = "Cryptography Should Be Hard to Use Improperly"
permalink = "/everyday-cryptography"
preview = "/images/2026-07-20-og.png"
date = 2026-07-20

[[posts]]
path = "2026-07-26-slop-proxy.typ"
title = "Don't Be a Slop Proxy"
tagline = "Do I Look Like Someone Who Doesn't Know How to Generate My Own Slop?"
permalink = "/slop-proxy"
preview = "/images/2026-07-26-og.png"
date = 2026-07-26
